sudo: required
dist: xenial

stages:
  - test
  - deploy

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=stable
  - HAXE_VERSION=nightly

install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  # - lix run travix flash
  - lix run travix java
  - lix run travix cpp
  - lix run travix cs
  - lix run travix php

jobs:
  include:
    # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
    - stage: deploy
      os: linux
      install:
        - npm i -g lix
        - lix download
      script: skip
      env:
        secure: GJJgZRNPiyQaqiSpstAGI9S2+q+zQiF+S0MWHiMTOXFOJ0irtrVCRZbTqYd1p+yVyFtShrRXV8U+/0AbM81WR+kVM732Db5m+3w7s7Vbv436NDvU10h5gHNQ6l9c7eKSY1UW+p2p4liHEA737x9HFexE1QFYdx/qp7LVpoDf+xY=
      after_success:
        - lix run travix install
        - lix run travix release
